### ISSUE TITLE
Store metrics using explicit schema

### ISSUE THREAD

**Issue by ants** [cybertec-postgresql/pgwatch#165]
In pgw2 data and tags are stored as jsonb. This duplicates schema information in every row, giving bad storage efficiency for uncompressed data. It also defeats timeseries compression mechanisms for compressed data. Additionally, any access to data needs to decompress the whole document instead of accessing just the necessary column, which is very important for columnar storage.

Storing series metadata (e.g. full query text) out-of-line in a separate table might also be a good idea.

TBD: measurements on real world data

**Comment by kmoppel** [comment]
My .02$ - in practice I think that extra data proliferation only becomes visible only with this `stat_statements` metric - and using TimescaleDB reduced old data heavily still (aroun ~10x) - so indeed, would be nice, but not sure if its worth the extra complexity as users on very high instance counts would probably prefer Prometheus anyways.
