### ISSUE TITLE
WebUI is not working from remote host

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch#526]
### Discussed in https://github.com/cybertec-postgresql/pgwatch/discussions/523

<div type='discussions-op-text'>

<sup>Originally posted by **ondar** August 26, 2024</sup>

When I log in from another computer on the network, I get Undefined error after pressing login:
![image](https://github.com/user-attachments/assets/cf7e72a9-da69-4d2b-b3b6-bae30fdd3b3e)
Seems UI is requesting response from localhost and not the remote server I run it from.

Backend and Grafana seems to be working just fine. What am I doing wrong?</div>

**Comment by ondar** [comment]
You can delete the 1st part about blank screen. That was already solved by you. Problem here is only 2nd part. Maybe next time I report errors I should do that separately 😁 Sorry for the confusion.

**Comment by pashagolub** [comment]
Would you please provide steps to reproduce the error? Thanks

**Comment by ondar** [comment]
Steps to reproduce: 
1. run pgwatch by included docker compose file on 1 computer in network
2. connect to pgwatch UI from different computer on the network

**Comment by pashagolub** [comment]
Ough, now I need to buy one more computer.... ;-)

**Comment by ondar** [comment]
I tried that again with freshly built docker image about an hour ago.

**Comment by ondar** [comment]
I did that using 2 virtual computers on 1 physical. Maybe you can try it from phone connected to the same wifi?

**Comment by ondar** [comment]
I guess there is some setting in UI that represent endpoint of backend pgwatch that is currently set to http://localhost:8080. This setting needs to be dynamicaly derived from host you call UI from or maybe set manually when deployed by env variable to host's external IP and port? Calling backend from frontend is tricky 😁

**Comment by pashagolub** [comment]
ok, thanks. There was an easier way to reproduce the issue: http://127.0.0.1:8080/

**Comment by ondar** [comment]
But I guess it still works if it finds backend at localhost:8080, if you run it from different device where there is nothing on port 8080 it will throw timeout but this timeout just show error message "Undefined" (as there is nothing in response body I guess?
