### ISSUE TITLE
Docker start fails with spawnerr: command at '/pgwatch/bootstrap/init_supervisor.sh' is not executable

### ISSUE THREAD

**Issue by TheDromundKaas** [cybertec-postgresql/pgwatch#562]
**Describe the bug**
Good morning Pavlo,

just wanted to test the docker image of pgwatch3. http://127.0.0.1:3000/dashboard/db/db-overview did not come up (15 minutes wait time so far). docker logs for the container shows:

> [tengelke@thinkpad docker]$ sudo docker logs 5a16f231b46e
> 2024-10-21 06:38:11,434 INFO Set uid to user 0 succeeded
> 2024-10-21 06:38:11,436 INFO RPC interface 'supervisor' initialized
> 2024-10-21 06:38:11,436 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2024-10-21 06:38:11,436 INFO supervisord started with pid 1
> 2024-10-21 06:38:12,437 INFO spawnerr: command at '/pgwatch/bootstrap/init_supervisor.sh' is not executable
> 2024-10-21 06:38:13,439 INFO spawnerr: command at '/pgwatch/bootstrap/init_supervisor.sh' is not executable
> 2024-10-21 06:38:15,441 INFO spawnerr: command at '/pgwatch/bootstrap/init_supervisor.sh' is not executable
> 2024-10-21 06:38:18,446 INFO spawnerr: command at '/pgwatch/bootstrap/init_supervisor.sh' is not executable
> 2024-10-21 06:38:18,446 INFO gave up: init_supervisor entered FATAL state, too many start retries too quickly

**To Reproduce**
> sudo docker run -d --name pw3 -p 5432:5432 -p 3000:3000 -p 8080:8080 -e PW_TESTDB=true cybertecpostgresql/pgwatch-demo

**Expected behavior**
WebUI at http://127.0.0.1:3000/dashboard/db/db-overview can be opened after a few minutes.

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Arch-like)
 - Browser: Firefox
 - Version 131.0.3

**Additional context**
I'm not very well versed in dockeresque, maybe I made a mistake. If not, hopefully this info helps.

Edit 1:
Cloning the repo I can see that the shell scripts in /docker/bootstrap are all non-executable:

> [tengelke@thinkpad bootstrap]$ ls -la *.sh
> -rw-r--r-- 1 tengelke tengelke  781 21. Okt 11:16 init_dbs.sh
> -rw-r--r-- 1 tengelke tengelke 2015 21. Okt 11:16 init_persistent_config.sh
> -rw-r--r-- 1 tengelke tengelke  318 21. Okt 11:16 init_supervisor.sh
> -rw-r--r-- 1 tengelke tengelke  417 21. Okt 11:16 init_test_monitored_db.sh

However, the shell scripts in /docker have the executable flag:

> [tengelke@thinkpad docker]$ ls -la *.sh
> -rwxr-xr-x 1 tengelke tengelke 359 21. Okt 11:16 build-docker-demo.sh
> -rwxr-xr-x 1 tengelke tengelke 349 21. Okt 11:16 build-docker.sh

**Comment by pashagolub** [comment]
Thanks for pointing this out! I pushed fixed images. Would you please retry? Thanks

**Comment by pashagolub** [comment]
And the correct link to dashboard is http://127.0.0.1:3000/d/db-overview/db-overview
