### ISSUE TITLE
Errors in logs 

### ISSUE THREAD

**Issue by krisavi** [cybertec-postgresql/pgwatch#582]
**Describe the bug**
I have no source configured without host nor without database. For some reason it seems to want to connect to config instance on postgres database or without any database and as root. 

**To Reproduce**
Not sure at the moment. Will try to recreate with smaller configuration. May be due to etcd3 configs or something wrong with specific source. Or at some point it saved source without proper configuration and kept trying to connect to it.

**Expected behavior**
Error to at least report if it is config db connection error or due to one of the configured sources. (source: sourcename) could help out a bit. For internal connections use (source: __internal__) or something alike. 

Such line is not that useful either. Maybe reference to some error code in code to help tracing where issues come up.  
`could not init connection, retrying on next iteration: %!w(<nil>)` 

Desktop (please complete the following information):
- pgwatch built on aarch64 MacOS for amd64 linux with #580 change.

**Additional context**
`journalctl -xef -u pgwatch3` output
```
Oct 31 21:56:11 pgwatch.krisavi.intra pgwatch[2104884]: 2024-10-31 21:56:11.752 [ERROR] [database:] [err:failed to connect to `user=root database=`: /var/run/postgresql/.s.PGSQL.5432 (/var/run/postgresql): server error: FATAL: role "root" does not exist (SQLSTATE 28000)] [host:/var/run/postgresql] [port:5432] [time:2.918807ms] Connect
Oct 31 21:56:11 pgwatch.krisavi.intra pgwatch[2104884]: 2024-10-31 21:56:11.752 [WARNING] could not init connection, retrying on next iteration: %!w(<nil>)
Oct 31 21:56:11 pgwatch.krisavi.intra pgwatch[2104884]: 2024-10-31 21:56:11.756 [ERROR] [database:postgres] [err:failed to connect to `user=pgwatch2 database=postgres`: /var/run/postgresql/.s.PGSQL.5432 (/var/run/postgresql): server error: FATAL: Peer authentication failed for user "pgwatch2" (SQLSTATE 28000)] [host:/var/run/postgresql] [port:5432] [time:3.583946ms] Connect
Oct 31 21:56:11 pgwatch.krisavi.intra pgwatch[2104884]: 2024-10-31 21:56:11.756 [WARNING] could not init connection, retrying on next iteration: %!w(<nil>)
```

**Comment by pashagolub** [comment]
What's the command line?

**Comment by krisavi** [comment]
`/usr/bin/pgwatch -s=postgresql://localhost:5432/pgwatch2_config?user=pgwatch2 --sink=postgresql://pgwatch2@localhost:6432/pgwatch_metric`

**Comment by pashagolub** [comment]
how about
```
/usr/bin/pgwatch -s=postgresql://pgwatch2@localhost:5432/pgwatch2_config --sink=postgresql://pgwatch2@localhost:6432/pgwatch_metric
```
