### ISSUE TITLE
YAML based sources are not updated properly

### ISSUE THREAD

**Issue by MichaelZhasil** [cybertec-postgresql/pgwatch#594]
**Describe the bug**
When editing configuration in sources.yaml for already monitored database, the change is never propagated into running instance.

**To Reproduce**
1. Create sources.yaml with wrong password for monitored database
2. Run PGWATCH in file based mode 
3. Edit sources - fix password
4. Wait till sources and metrics are refreshed  

**Expected behavior**
After refresh of sources and metrics the pgwatch will connect to databse with new credentials

**Additional context**
Adding new database to sources.yaml, or removing works properly and the database is added/removed from monitored dbs on refresh

**Comment by pashagolub** [comment]
Thanks for the report. Would you please confirm #597 fixes the bug for you?

Thanks in advance!

**Comment by MichaelZhasil** [comment]
Hello, yes it fixes the issue, everything works like a charm.
Thank you
